[package]
name = "tysm"
version = "0.1.0"
edition = "2021"
description = "A strongly-typed Rust client for OpenAI's ChatGPT API"
license = "MIT"
homepage = "https://github.com/not-pizza/tysm"
repository = "https://github.com/not-pizza/tysm"
readme = "README.md"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.75"
schemars = { version = "0.8.12", features = ["preserve_order"] }
thiserror = "2.0.9"
tynm = "0.1.10"
